# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua



$mainMod = SUPER
$terminal = alacritty
$fileManager = ranger
$menu = wofi

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, B, exec, env MOZ_ENABLE_WAYLAND=1  zen-browser
bind = $mainMod, right, workspace, +1
bind = $mainMod, left, workspace, -1
windowrule = pseudo 1
exec-once = hyprpaper
monitor=,preferred,auto,1
